version: "3.4"

# Development environment override
services:
  php:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      target: app_php_dev
    volumes:
      - ../:/srv/app
      - ./php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
    environment:
      PHP_IDE_CONFIG: "serverName=speaky"
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      - host.docker.internal:host-gateway
